# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  build:
    runs-on: [windows-latest]
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ">=10.15.0"
          # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
          architecture: "x86"
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: yarn install
        run: yarn
        working-directory: packages/server
      - name: yarn build
        run: yarn build    
